name: Run Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Permet de lancer le test manuellement depuis l'interface

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/python-python@v5
      with:
        python-version: "3.11"

    - name: Test Swap Checker
      run: |
        python src/swap_checker.py
